package com.travellog.common;

public enum ErrorCode {
	VALIDATION_FAILED,
	USERNAME_TAKEN,
	EMAIL_IN_USE,
	INVALID_CREDENTIALS,
	ACCOUNT_DISABLED,
	UNAUTHORIZED,
	JOURNEY_NOT_FOUND,
	EVENT_NOT_FOUND,
	PHOTO_NOT_FOUND,
	INTERNAL_ERROR
}
